<?php

namespace App\Support;

/**
 * Canonical Privacy Policy and Terms & Conditions content for the public
 * marketing site. Mirrors the structure of MadFanStory but renders through
 * Fan/Legal.jsx (a numbered-section document layout) rather than the
 * card/band narrative layout StaticPage.jsx uses — legal text reads as
 * clauses, not marketing copy.
 */
class MadFanLegal
{
    /**
     * @return list<string>
     */
    public static function slugs(): array
    {
        return ['privacy', 'terms'];
    }

    /**
     * @return array{title: string, effective_date: string, intro: list<string>, sections: list<array{heading: string, body?: list<string>, bullets?: list<string>}>}
     */
    public static function page(string $slug): array
    {
        return match ($slug) {
            'privacy' => self::privacy(),
            'terms' => self::terms(),
            default => abort(404),
        };
    }

    private static function privacy(): array
    {
        return [
            'title' => 'Privacy Policy',
            'effective_date' => 'August 25, 2026',
            'intro' => [
                'Mad Fan ("Mad Fan", "we", "us", or "our") operates madfan.xyz and the Mad Fan applications, including the Season campaign, the Fan Passport, and Mad Fan Social (together, the "Platform"). This Privacy Policy explains what personal information we collect, why we collect it, how we use and share it, and the choices and rights you have.',
                'By creating an account or otherwise using the Platform, you agree to the collection and use of information in accordance with this Policy. If you do not agree, please do not use the Platform.',
            ],
            'sections' => [
                [
                    'heading' => 'Information We Collect',
                    'body' => [
                        'We collect information you provide directly, information generated by your use of the Platform, and information from third parties you choose to connect.',
                    ],
                    'bullets' => [
                        'Account information — name, email address, username, handle, date of birth, password (stored as a salted hash, never in plain text), and profile photo.',
                        'Fan identity data — your favourite club and fandom, Fan ID, loyalty points, streaks, tier, and the full history of point-earning activity that makes up your Fan Passport.',
                        'Content you create — posts, replies, likes, reposts, chat messages, and any images or media you upload to the terrace or your club\'s rooms.',
                        'Connected social accounts — if you link an X (Twitter), Discord, or Telegram account for task verification, we receive the minimum information that platform provides to confirm the connection (typically your handle or user ID), not your password or private messages.',
                        'Transaction data — records of match ticket purchases, kit/shop orders, and referral activity, including order identifiers and delivery information where relevant. We do not store full payment card numbers; card processing is handled by our payment processor.',
                        'Usage and device data — pages viewed, features used, approximate location derived from IP address, browser type, device identifiers, and log data collected automatically when you use the Platform.',
                        'Communications — messages you send us for support, feedback, or partnership inquiries, and records of our replies.',
                    ],
                ],
                [
                    'heading' => 'How We Use Your Information',
                    'body' => [
                        'We use the information we collect to:',
                    ],
                    'bullets' => [
                        'Create and maintain your account, your Fan Passport, and your loyalty ledger.',
                        'Operate core features — the terrace feed, club chat rooms, Stage voice rooms, match tickets, the shop, and Season campaigns.',
                        'Calculate loyalty points, streaks, tiers, and leaderboard standing, and detect and prevent fraudulent or gamed activity.',
                        'Personalize your experience, including club-scoped content and fan suggestions.',
                        'Send transactional communications (verification emails, security alerts, order confirmations) and, where you have opted in, product updates and campaign announcements.',
                        'Monitor, secure, and improve the Platform, including debugging, analytics, and capacity planning.',
                        'Comply with legal obligations and enforce our Terms & Conditions.',
                    ],
                ],
                [
                    'heading' => 'Legal Bases for Processing',
                    'body' => [
                        'Where the General Data Protection Regulation (GDPR) or a similar law applies, we rely on the following legal bases: performance of a contract (providing the Platform you signed up for), legitimate interests (keeping the Platform secure and improving it), consent (for optional marketing communications and certain cookies), and compliance with legal obligations.',
                    ],
                ],
                [
                    'heading' => 'How We Share Information',
                    'body' => [
                        'We do not sell your personal information. We share information only in the following circumstances:',
                    ],
                    'bullets' => [
                        'With service providers who help us operate the Platform — hosting, email delivery, payment processing, and analytics — under contracts that limit their use of your data to providing services to us.',
                        'With clubs and campaign partners in aggregated or de-identified form (for example, "1,204 Arsenal fans completed Week 3"), never as personally identifiable records without your consent.',
                        'With other users, to the extent you choose to make information public — your handle, posts, replies, club allegiance, and Passport standing are visible to other fans by design.',
                        'When required by law, to comply with legal process, or to protect the rights, property, or safety of Mad Fan, our users, or the public.',
                        'In connection with a merger, acquisition, financing, or sale of assets, subject to this Policy continuing to apply to your information.',
                    ],
                ],
                [
                    'heading' => 'Social Media Account Connections',
                    'body' => [
                        'Season campaigns may ask you to connect an X (Twitter), Discord, or Telegram account so that we can verify completion of social tasks (for example, following an account or joining a server). We access only what the connected platform\'s API exposes for that verification and never post on your behalf without a separate, explicit action from you. You can disconnect a linked account at any time from Connect Accounts in your settings.',
                    ],
                ],
                [
                    'heading' => 'Cookies and Tracking Technologies',
                    'body' => [
                        'We use cookies and similar technologies to keep you signed in, remember your preferences, understand how the Platform is used, and measure the effectiveness of campaigns. You can control cookies through your browser settings; disabling essential cookies may prevent parts of the Platform from working.',
                    ],
                ],
                [
                    'heading' => 'Data Retention',
                    'body' => [
                        'We retain your account and Passport data for as long as your account is active, since your loyalty history is the product itself. If you delete your account, we remove or anonymize personal information within a reasonable period, except where we are required to retain it for legal, tax, fraud-prevention, or dispute-resolution purposes.',
                    ],
                ],
                [
                    'heading' => 'Your Privacy Rights',
                    'body' => [
                        'Depending on where you live, you may have the right to access, correct, delete, or export your personal information, to object to or restrict certain processing, and to withdraw consent for optional communications at any time. Residents of the European Economic Area, the United Kingdom, and California (and other states with similar laws) have specific statutory rights under GDPR, UK GDPR, and the CCPA/CPRA respectively. To exercise any of these rights, contact us using the details below — we will respond within the timeframe required by applicable law.',
                    ],
                ],
                [
                    'heading' => "Children's Privacy",
                    'body' => [
                        'The Platform is not directed to children under 16, and we do not knowingly collect personal information from children under that age. If you believe a child has provided us with personal information, contact us and we will take steps to delete it.',
                    ],
                ],
                [
                    'heading' => 'Data Security',
                    'body' => [
                        'We use industry-standard technical and organizational measures — including encryption in transit, hashed credentials, and access controls — to protect your information. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.',
                    ],
                ],
                [
                    'heading' => 'International Data Transfers',
                    'body' => [
                        'Mad Fan is built from Lagos, Nigeria with a global fan base. Your information may be processed in countries other than your own, including countries that may not have data protection laws equivalent to those in your jurisdiction. Where required, we use appropriate safeguards, such as standard contractual clauses, for these transfers.',
                    ],
                ],
                [
                    'heading' => 'Third-Party Links',
                    'body' => [
                        'The Platform may link to third-party websites or services, including club websites, ticketing partners, and social media platforms. We are not responsible for the privacy practices of those third parties, and we encourage you to review their policies.',
                    ],
                ],
                [
                    'heading' => 'Changes to This Policy',
                    'body' => [
                        'We may update this Privacy Policy from time to time. If we make material changes, we will notify you by email or through a notice on the Platform before the changes take effect. The "Effective date" above shows when this Policy was last revised.',
                    ],
                ],
                [
                    'heading' => 'Contact Us',
                    'body' => [
                        'If you have questions about this Privacy Policy or want to exercise your privacy rights, contact us at privacy@madfan.xyz or career.madfan@gmail.com.',
                    ],
                ],
            ],
        ];
    }

    private static function terms(): array
    {
        return [
            'title' => 'Terms & Conditions',
            'effective_date' => 'August 25, 2026',
            'intro' => [
                'These Terms & Conditions ("Terms") govern your access to and use of madfan.xyz and the Mad Fan applications, including the Season campaign, the Fan Passport, and Mad Fan Social (together, the "Platform"), operated by Mad Fan ("Mad Fan", "we", "us", or "our").',
                'By creating an account or using the Platform in any way, you agree to be bound by these Terms and by our Privacy Policy, which is incorporated by reference. If you do not agree, do not use the Platform.',
            ],
            'sections' => [
                [
                    'heading' => 'Eligibility',
                    'body' => [
                        'You must be at least 16 years old to create an account. By registering, you represent that you meet this requirement and that all information you provide is accurate and current. Each person may hold only one account; we reserve the right to suspend or merge accounts that violate this rule.',
                    ],
                ],
                [
                    'heading' => 'Account Registration & Security',
                    'body' => [
                        'You are responsible for maintaining the confidentiality of your password and for all activity that occurs under your account. Notify us immediately at the contact address below if you suspect unauthorized access. We are not liable for losses caused by unauthorized use of your account that results from your failure to safeguard your credentials.',
                    ],
                ],
                [
                    'heading' => 'The Mad Fan Platform',
                    'body' => [
                        'The Platform brings together several systems that fans participate in: the Season campaign (daily check-ins, referrals, and tasks), Mad Fan Social (a club-scoped feed and chat), the Fan Passport (your loyalty identity), match tickets, and the kit shop. Not every feature described in our marketing materials is available to every user at every time — some capabilities are still being built and are marked accordingly where relevant. We may add, change, or discontinue features at our discretion.',
                    ],
                ],
                [
                    'heading' => 'Loyalty Points, Passport & Rewards',
                    'body' => [
                        'Loyalty points, streaks, tiers, and any in-Platform currency ("Loyalty Points") are a record of your participation and have no cash value. Loyalty Points cannot be purchased, sold, transferred between accounts, exchanged for cash, or redeemed outside the Platform. We may adjust, cap, or reverse Loyalty Points that we determine, in our reasonable discretion, were earned through fraud, automation, exploitation of a bug, or violation of these Terms. We may modify the earning rules, tiers, or rewards catalogue at any time, and we may retire or replace the Loyalty Points system entirely, subject to reasonable notice where practical.',
                    ],
                ],
                [
                    'heading' => 'Season Campaigns & Promotions',
                    'body' => [
                        'Season campaigns, giveaways, and leaderboard competitions ("Promotions") are subject to these Terms and any additional rules published for that specific Promotion, which form part of these Terms for the duration of that Promotion. We may modify, suspend, or cancel a Promotion, and disqualify any entrant we reasonably believe has violated its rules or these Terms, including through the use of bots, multiple accounts, or purchased engagement.',
                    ],
                ],
                [
                    'heading' => 'User Content & Conduct',
                    'body' => [
                        'You retain ownership of the content you post to the terrace, club chat rooms, or elsewhere on the Platform ("User Content"). By posting User Content, you grant Mad Fan a worldwide, non-exclusive, royalty-free, sublicensable licence to host, store, reproduce, display, and distribute it as necessary to operate and promote the Platform. You are solely responsible for your User Content and represent that you have the rights necessary to post it.',
                    ],
                    'bullets' => [
                        'Do not post content that is illegal, defamatory, harassing, hateful, sexually explicit, or that infringes another person\'s intellectual property or privacy rights.',
                        'Do not impersonate another person or club, or misrepresent your affiliation with any person or organization.',
                        'Do not use bots, scripts, or automation to farm Loyalty Points, spam the feed or chat, or manipulate leaderboards.',
                        'Do not attempt to gain unauthorized access to the Platform, other accounts, or our systems, or interfere with the Platform\'s normal operation.',
                        'Do not use the Platform for gambling, financial solicitation, or any unlawful purpose.',
                    ],
                ],
                [
                    'heading' => 'Moderation & Enforcement',
                    'body' => [
                        'We may remove User Content, restrict features, suspend, or terminate accounts that violate these Terms, at our discretion and without prior notice where we believe it is necessary to protect the Platform or our users. Reports of infringing or abusive content can be sent to the contact address below.',
                    ],
                ],
                [
                    'heading' => 'Intellectual Property',
                    'body' => [
                        'The Platform, including its design, software, trademarks ("Mad Fan", the Mad Fan logo, "THE BOARD", and related marks), and all content we create, is owned by Mad Fan or our licensors and is protected by intellectual property laws. Club names, crests, and kit imagery remain the property of their respective clubs and are used for identification purposes within the Platform. Except as expressly permitted, you may not copy, modify, distribute, or create derivative works from any part of the Platform without our prior written consent.',
                    ],
                ],
                [
                    'heading' => 'Purchases',
                    'body' => [
                        'Match tickets and shop orders are purchases subject to the price, availability, and delivery terms shown at checkout. Payment processing is handled by third-party payment providers; by making a purchase you also agree to their applicable terms. Except where required by law or stated otherwise at the time of purchase, sales are final. Match tickets are non-transferable outside the Platform\'s own transfer or resale features, where offered.',
                    ],
                ],
                [
                    'heading' => 'Third-Party Services & Links',
                    'body' => [
                        'The Platform may integrate with or link to third-party services, including X (Twitter), Discord, Telegram, and payment processors. Your use of those services is governed by their own terms and privacy policies, and we are not responsible for their content, availability, or practices.',
                    ],
                ],
                [
                    'heading' => 'Termination',
                    'body' => [
                        'You may stop using the Platform and request account deletion at any time by contacting us. We may suspend or terminate your access to the Platform, with or without notice, if we believe you have violated these Terms, created risk or legal exposure for us, or if we discontinue the Platform. Provisions that by their nature should survive termination — including intellectual property, disclaimers, limitation of liability, and dispute resolution — will survive.',
                    ],
                ],
                [
                    'heading' => 'Disclaimers',
                    'body' => [
                        'THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT THE PLATFORM WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE. WE DO NOT GUARANTEE THAT ANY PARTICULAR LEVEL OF LOYALTY POINTS, REWARDS, OR PROMOTION OUTCOME WILL BE AVAILABLE OR ACHIEVED.',
                    ],
                ],
                [
                    'heading' => 'Limitation of Liability',
                    'body' => [
                        'TO THE MAXIMUM EXTENT PERMITTED BY LAW, MAD FAN AND ITS OFFICERS, EMPLOYEES, AND PARTNERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, GOODWILL, OR LOYALTY POINTS, ARISING OUT OF OR RELATED TO YOUR USE OF THE PLATFORM. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING FROM THESE TERMS OR THE PLATFORM WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM AROSE, OR (B) ONE HUNDRED UNITED STATES DOLLARS (US$100). SOME JURISDICTIONS DO NOT ALLOW THESE LIMITATIONS, SO THEY MAY NOT APPLY TO YOU.',
                    ],
                ],
                [
                    'heading' => 'Indemnification',
                    'body' => [
                        'You agree to indemnify and hold Mad Fan harmless from any claims, damages, liabilities, and expenses (including reasonable legal fees) arising from your use of the Platform, your User Content, or your violation of these Terms or any law or third-party right.',
                    ],
                ],
                [
                    'heading' => 'Governing Law & Dispute Resolution',
                    'body' => [
                        'These Terms are governed by the laws of the Federal Republic of Nigeria, without regard to conflict-of-law principles, except where mandatory local consumer-protection law provides otherwise. Before filing a claim, you agree to contact us so we can attempt to resolve the dispute informally. Any dispute that cannot be resolved informally will be subject to the exclusive jurisdiction of the courts of Lagos, Nigeria, unless applicable law in your place of residence gives you the right to bring a claim elsewhere.',
                    ],
                ],
                [
                    'heading' => 'Changes to These Terms',
                    'body' => [
                        'We may update these Terms from time to time. If we make material changes, we will notify you by email or through a notice on the Platform before the changes take effect. Continued use of the Platform after changes take effect constitutes acceptance of the revised Terms.',
                    ],
                ],
                [
                    'heading' => 'Miscellaneous',
                    'body' => [
                        'If any provision of these Terms is found unenforceable, the remaining provisions will remain in full effect. Our failure to enforce any right or provision is not a waiver of that right. You may not assign these Terms without our consent; we may assign them in connection with a merger, acquisition, or sale of assets. These Terms, together with our Privacy Policy and any Promotion-specific rules, constitute the entire agreement between you and Mad Fan regarding the Platform.',
                    ],
                ],
                [
                    'heading' => 'Contact Us',
                    'body' => [
                        'Questions about these Terms can be sent to legal@madfan.xyz or career.madfan@gmail.com.',
                    ],
                ],
            ],
        ];
    }
}
